# Generated by Django 5.0.7 on 2024-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=100, unique=True)),
                ('batch_name', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_stage', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('exam_year', models.IntegerField()),
                ('question_part', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(max_length=100)),
                ('question_sub_type', models.CharField(max_length=100)),
                ('question_part_first_part', models.TextField(blank=True, null=True)),
                ('list_1_present', models.BooleanField(default=False)),
                ('list_2_present', models.BooleanField(default=False)),
                ('list_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('list_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('question_part_first_part_list', models.TextField(blank=True, null=True)),
                ('list_1_row1', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row1', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row2', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row2', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row3', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row3', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row4', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row4', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row5', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row5', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row6', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row6', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row7', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row7', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row8', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row8', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row9', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row9', models.CharField(blank=True, max_length=255, null=True)),
                ('question_part_third_part', models.TextField(blank=True, null=True)),
                ('answer_option_a', models.TextField(blank=True, null=True)),
                ('answer_option_b', models.TextField(blank=True, null=True)),
                ('answer_option_c', models.TextField(blank=True, null=True)),
                ('answer_option_d', models.TextField(blank=True, null=True)),
                ('correct_answer_choice', models.CharField(blank=True, max_length=1, null=True)),
                ('correct_answer_description', models.TextField(blank=True, null=True)),
                ('marks', models.FloatField()),
                ('negative_marks', models.FloatField()),
                ('language', models.CharField(max_length=100)),
                ('script', models.TextField(blank=True, null=True)),
                ('degree_of_difficulty', models.CharField(max_length=100)),
            ],
        ),
    ]
