# Generated by Django 5.0.7 on 2024-07-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hia_question_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='list_1_present',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='list_2_present',
        ),
    ]
