# Generated by Django 5.0.7 on 2024-07-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hia_question_bank_app', '0002_remove_questionbank_list_1_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='negative_marks',
            field=models.FloatField(default=0.0),
        ),
    ]
