# Generated by Django 5.0.7 on 2024-07-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hia_question_bank_app', '0003_alter_questionbank_language_alter_questionbank_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='batch_name',
            new_name='type_of_question',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='question_part_first_part_list',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='question_type',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_a_data1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_a_data2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_a_data3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_a_data4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_b_data1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_b_data2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_b_data3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_b_data4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_c_data1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_c_data2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_c_data3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_c_data4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_d_data1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_d_data2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_d_data3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='head_d_data4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Question Images'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='table_head_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='table_head_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='table_head_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='table_head_d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='exam_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
