# Generated by Django 5.0.7 on 2024-08-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hia_question_bank_app', '0004_rename_batch_name_questionbank_type_of_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='assertion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
